<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Performance Insights Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 15px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        .metric {
            margin-bottom: 10px;
        }
        .metric-label {
            font-weight: bold;
            color: #7f8c8d;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f5f6fa;
        }
        .chart {
            margin: 20px 0;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Performance Insights Report</h1>
        <p>{{ $team->name }}</p>
        <p>Period: {{ $period['start'] }} - {{ $period['end'] }}</p>
    </div>

    <div class="section">
        <h2 class="section-title">Account Overview</h2>
        @foreach($account_insights as $insight)
        <div class="metric">
            <span class="metric-label">Platform:</span> {{ $insight->socialAccount->platform }}<br>
            <span class="metric-label">Followers:</span> {{ number_format($insight->followers) }}<br>
            <span class="metric-label">Posts:</span> {{ number_format($insight->posts_count) }}<br>
            <span class="metric-label">Reach:</span> {{ number_format($insight->reach) }}<br>
            <span class="metric-label">Engagement Rate:</span> {{ $insight->engagement_rate }}%
        </div>
        <hr>
        @endforeach
    </div>

    <div class="section">
        <h2 class="section-title">Top Performing Posts</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Platform</th>
                    <th>Type</th>
                    <th>Likes</th>
                    <th>Comments</th>
                    <th>Shares</th>
                    <th>Views</th>
                    <th>Engagement</th>
                </tr>
            </thead>
            <tbody>
                @foreach($post_insights as $insight)
                <tr>
                    <td>{{ $insight->platform }}</td>
                    <td>{{ $insight->post->post_type }}</td>
                    <td>{{ number_format($insight->likes) }}</td>
                    <td>{{ number_format($insight->comments) }}</td>
                    <td>{{ number_format($insight->shares) }}</td>
                    <td>{{ number_format($insight->views) }}</td>
                    <td>{{ $insight->engagement_rate }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2 class="section-title">Content Analysis</h2>
        <div class="metric">
            <span class="metric-label">Best Performing Content Type:</span><br>
            @foreach($content_analysis as $type => $stats)
            {{ ucfirst($type) }}: {{ $stats['engagement_rate'] }}% avg. engagement<br>
            @endforeach
        </div>
    </div>

    <div class="section">
        <h2 class="section-title">Best Posting Times</h2>
        <div class="metric">
            @foreach($best_times as $time)
            {{ $time['hour'] }}:00 - Avg. Engagement: {{ $time['engagement_rate'] }}%<br>
            @endforeach
        </div>
    </div>

    <div class="section">
        <h2 class="section-title">Growth Metrics</h2>
        <div class="metric">
            <span class="metric-label">Follower Growth:</span> {{ $growth_metrics['follower_growth'] }}%<br>
            <span class="metric-label">Engagement Growth:</span> {{ $growth_metrics['engagement_growth'] }}%<br>
            <span class="metric-label">Reach Growth:</span> {{ $growth_metrics['reach_growth'] }}%
        </div>
    </div>

    <div class="footer">
        <p style="text-align: center; font-size: 12px; color: #7f8c8d;">
            Generated by PostFlex AI on {{ now()->format('Y-m-d H:i:s') }}
        </p>
    </div>
</body>
</html> 